# Generated by Django 5.0.4 on 2024-04-05 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Aluno',
            new_name='Alunos',
        ),
    ]
