# Generated by Django 5.0.4 on 2024-04-05 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0002_rename_aluno_alunos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alunos',
            name='foto',
        ),
        migrations.AddField(
            model_name='alunos',
            name='sexo',
            field=models.CharField(default='Masculino', max_length=20),
        ),
    ]
