# Generated by Django 5.0.4 on 2024-04-05 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0004_alter_alunos_data_nascimento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alunos',
            old_name='data_nascimento',
            new_name='dt_nasc',
        ),
    ]
